version: "3.7"
services:
  apache:
    restart: always
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./www/cgi-bin:/var/www/html/cgi-bin
      - ./www/tccm_html:/var/www/html/tccm_html
